# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='won',
            field=models.CharField(default='ongoing', max_length=10),
        ),
    ]
