# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_auto_20171023_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='won',
            new_name='status',
        ),
    ]
